In [ ]:
# ============================================================
# Project           : International Debt Analysis System 
# Phase             : EDA
# Author            : Rajesh
# Description       : To perform EDA on cleaned data
# ============================================================

In [1]:
import pandas as pd
import os

In [2]:
processed_path = r'D:\Guvi_DS_BC\Mini_Projects\InternationalDebtAnalysisSystem\data\Processed'

df_long = pd.read_csv(os.path.join(processed_path,"cleaned_debt_data.csv"),
                      dtype={
                          'Country Name': 'category',
                          'Country Code': 'category',
                          'Series Name': 'category',
                          'Series Code': 'category'
                      })
df_country = pd.read_csv(os.path.join(processed_path,"cleaned_country_meta.csv"))
df_series = pd.read_csv(os.path.join(processed_path,"cleaned_series_meta.csv"))


print("Shape of long DF:",df_long.shape)
print("Shape of country DF:",df_country.shape)
print("Shape of series DF",df_series.shape)

Shape of long DF: (1246935, 6)
Shape of country DF: (120, 4)
Shape of series DF (574, 3)

In [13]:
print(df_long['Country Code'].head())
print(df_country['Code'].head())

0    ALB
1    ALB
2    ALB
3    ALB
4    ALB
Name: Country Code, dtype: category
Categories (134, str): ['AGO       ', 'ALB       ', 'ARG       ', 'ARM       ', ..., 'MNE       ', 'IRQ       ', 'SUR       ', 'GNQ       ']
0    AFG
1    ALB
2    DZA
3    AGO
4    ARG
Name: Code, dtype: str

In [15]:
df_country['Code'] = df_country['Code'].str.strip()
df_long['Country Code'] = df_long['Country Code'].str.strip()

In [16]:
print(df_long['Country Code'].head())
print(df_country['Code'].head())

0    ALB
1    ALB
2    ALB
3    ALB
4    ALB
Name: Country Code, dtype: object
0    AFG
1    ALB
2    DZA
3    AGO
4    ARG
Name: Code, dtype: str

In [19]:
df_long_filtered = df_long[df_long['Country Code'].isin(df_country['Code'])]
df_long_filtered.shape

(1060074, 6)

In [3]:
#Finding the statistical summary
df_long.describe()

               year    debt_value
count  1.246935e+06  1.246935e+06
mean   2.012077e+03  9.873517e+09
std    7.218057e+00  2.147381e+11
min    2.000000e+03 -5.270000e+11
25%    2.006000e+03  3.018800e+00
50%    2.012000e+03  1.812543e+07
75%    2.018000e+03  4.312734e+08
max    2.024000e+03  3.820000e+13

In [6]:
df_long[df_long['debt_value']<0].shape

(132799, 6)

In [8]:
df_long[df_long['debt_value']<0]['Series Name'].value_counts().head(5)

Series Name
Current account balance (current US$)                                           2429
OPS, official creditors (NTR, current US$)                                      1721
Net transfers on external debt, other public sector (PPG) (NTR, current US$)    1706
PPG, bilateral (NTR, current US$)                                               1630
PS, bilateral (NTR, current US$)                                                1627
Name: count, dtype: int64

In [ ]:
#Country_wise Analysis

df_long.groupby('Country Name')['debt_value'].sum()

In [ ]:
country_debt = df_long_filtered.groupby('Country Name')['debt_value'].sum().reset_index()
country_debt.columns = ['Country Name','Total debt']
country_debt = country_debt.sort_values('Total debt',ascending=False)
#top_10 Countries
country_debt.head(10)

     Country Name    Total debt
22          China  6.083933e+14
49          India  1.856458e+14
14         Brazil  1.831054e+14
68         Mexico  1.822371e+14
50      Indonesia  1.165435e+14
105       Turkiye  1.155918e+14
3       Argentina  6.912848e+13
100      Thailand  5.145560e+13
92   South Africa  4.581863e+13
23       Colombia  4.371066e+13

In [23]:
#bottom_10_countries
country_debt.tail(10)

                       Country Name    Total debt
119               Equatorial Guinea  2.325492e+11
101                     Timor-Leste  2.077726e+11
95   St. Vincent and the Grenadines  2.075162e+11
85                            Samoa  1.778766e+11
24                          Comoros  1.586370e+11
29                         Dominica  1.565170e+11
90                  Solomon Islands  1.564889e+11
110                         Vanuatu  1.415127e+11
86            Sao Tome and Principe  1.211597e+11
103                           Tonga  8.419110e+10

In [ ]:
import plotly.express as px
fig = px.bar(country_debt.head(10), x='Country Name', y='Total debt',
             title='Top 10 Countries by Total Debt',
             color='Total debt',
             text='Total debt')

fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig.update_layout(xaxis_tickangle=-45)

fig.show()

In [ ]:
#Indicator-wise analysis

In [33]:
indicator_debt = df_long_filtered.groupby('Series Name')['debt_value'].sum().reset_index()
indicator_debt.columns = ['Series Name','Total Debt Value']
indicator_debt = indicator_debt.sort_values(['Total Debt Value'],ascending=False)
indicator_debt.head(10)

                                           Series Name  Total Debt Value
199                                  GNI (current US$)      5.086241e+14
210  Imports of goods, services and primary income ...      1.372848e+14
117  Exports of goods, services and primary income ...      1.299702e+14
132     External debt stocks, total (DOD, current US$)      1.255481e+14
566        Total reserves (includes gold, current US$)      1.071028e+14
123  External debt stocks, long-term (DOD, current ...      8.960399e+13
133  External debt stocks, variable rate (DOD, curr...      5.560520e+13
129  External debt stocks, public and publicly guar...      4.938917e+13
125  External debt stocks, long-term public sector ...      4.922593e+13
130  External debt stocks, public sector (PPG) (DOD...      4.920700e+13

In [38]:
fig = px.bar(indicator_debt.head(10), x='Total Debt Value', y='Series Name',
             title='Top 10 Indicators by Total Debt',
             orientation='h',
             color='Total Debt Value',
             text='Total Debt Value')

fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_range=[0, indicator_debt['Total Debt Value'].max() * 1.2],
    margin=dict(l=300)
)

fig.show()

In [47]:

#Year-wise Analysis
yearwise_debt = df_long_filtered.groupby('year')['debt_value'].sum().reset_index()
yearwise_debt.columns = ['Years','Total Debt']
yearwise_debt = yearwise_debt.sort_values('Total Debt',ascending=False)
yearwise_debt.head(10)

    Years    Total Debt
24   2024  1.667928e+14
21   2021  1.587238e+14
23   2023  1.586773e+14
22   2022  1.529928e+14
20   2020  1.419786e+14
19   2019  1.382011e+14
18   2018  1.340434e+14
17   2017  1.284896e+14
14   2014  1.138786e+14
16   2016  1.122992e+14

In [49]:
yearwise_debt = yearwise_debt.sort_values('Years', ascending=True)

fig = px.line(yearwise_debt, x='Years', y='Total Debt',
              title='Global Debt Trend (2000-2024)',
              markers=True,
              )

fig.update_traces(texttemplate='%{text:.2s}', textposition='top center')
fig.show()

In [ ]:
#Region-wise analysis

In [50]:
df_merged = pd.merge(df_long_filtered,df_country,left_on='Country Code',right_on='Code')
df_merged.shape

(1060074, 10)

In [51]:
df_merged.head(5)

,Country Name,Country Code,Series Name,Series Code,year,debt_value,Code,Long Name,Income Group,Region
0,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,10.5454,ALB,Republic of Albania,Upper middle income,Europe & Central Asia
1,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,10.5454,ALB,Republic of Albania,Upper middle income,Europe & Central Asia
2,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,0.0000,ALB,Republic of Albania,Upper middle income,Europe & Central Asia
3,Albania,ALB,Average grant element on new external debt com...,DT.GRE.DPPG,2000,25.7609,ALB,Republic of Albania,Upper middle income,Europe & Central Asia
4,Albania,ALB,Average grant element on new external debt com...,DT.GRE.OFFT,2000,25.7609,ALB,Republic of Albania,Upper middle income,Europe & Central Asia

In [52]:
region_debt = df_merged.groupby('Region')['debt_value'].sum().reset_index()
region_debt.columns = ['Region', 'Total Debt']
region_debt = region_debt.sort_values('Total Debt', ascending=False)
print(region_debt)

                       Region    Total Debt
0         East Asia & Pacific  8.800197e+14
2   Latin America & Caribbean  5.700321e+14
1       Europe & Central Asia  2.573784e+14
4                  South Asia  2.323271e+14
5          Sub-Saharan Africa  2.253239e+14
3  Middle East & North Africa  1.758339e+14

In [53]:
fig = px.pie(region_debt, values='Total Debt', names='Region',
             title='Debt Distribution by Region')
fig.show()

In [54]:
Income_group_debt = df_merged.groupby('Income Group')['debt_value'].sum().reset_index()
Income_group_debt.columns = ['Income Group', 'Total Debt']
Income_group_debt = Income_group_debt.sort_values('Total Debt', ascending=False)
print(Income_group_debt)

          Income Group    Total Debt
3  Upper middle income  1.672614e+15
2  Lower middle income  6.042645e+14
1           Low income  5.309840e+13
4              unknown  9.948968e+12
0          High income  9.894542e+11

In [55]:
fig = px.pie(Income_group_debt,values='Total Debt',names='Income Group',
             title='Debt Distribution by Region')

fig.show()